### ISSUE TITLE
Log show warning with iOS file

### ISSUE THREAD

**Issue by akino0910** [LeonBlade/xnbcli#10]
Like my title, I hope you will support it soon!
It can unpack file but when pack to XNB file, it has a large size (I'm doesn't change anything).

Warning:
![warning](https://user-images.githubusercontent.com/20903125/54992069-f0127e80-4ff0-11e9-81c2-28d15631cb0e.jpg)

Original Size:
![ORG_size](https://user-images.githubusercontent.com/20903125/54992399-c60d8c00-4ff1-11e9-8c21-3eed8215e6eb.jpg)

After Pack size:
![After_pack_size](https://user-images.githubusercontent.com/20903125/54992425-d7ef2f00-4ff1-11e9-8f00-4291425c6332.jpg)

**Comment by akino0910** [comment]
Here with debug mod:
![warning_debug](https://user-images.githubusercontent.com/20903125/55003596-442a5c80-500b-11e9-9861-cad580265b9e.jpg)

**Comment by LeonBlade** [comment]
It was just to test to see what the debug says.  This is a simple fix.  However, the increased size will not impact anything.  I will push out an update.

**Comment by akino0910** [comment]
OK, thank you, have a good day! I will waiting for it ;)

**Comment by LeonBlade** [comment]
The release is live, let me know if it works.

**Comment by akino0910** [comment]
I work really good now, thanks for your work hard!
