### ISSUE TITLE
bmfont type *.xml file couldn't repack

### ISSUE THREAD

**Issue by BlackRussians** [LeonBlade/xnbcli#15]
It was perfectly working when i unpack *.xnb to xml (*.fnt from bmfont)
but I couldn't pack that file again. even though I repacked a file, it still looked same after I packed.

These are pictures after I unpacked it and repacked.

<img src="https://i.imgur.com/qTgqGGr.jpg" width="90%"></img>

<img src="https://i.imgur.com/cW4pl5p.jpg" width="90%"></img>

**Comment by LeonBlade** [comment]
Do you get an error in game?
