### ISSUE TITLE
missing xnbcli.exe

### ISSUE THREAD

**Issue by matheusleao92** [LeonBlade/xnbcli#16]
Running unpack.bat in windows returns a "command not recognized" error for xnbcli.exe
I can't find this executable anywhere in the project. Is there some script I need to compile first?

Simply downloading the project and running the bat as per instructions doesn't work, unless I'm missing something obvious...

**Comment by LeonBlade** [comment]
Make sure you download from the releases.  https://github.com/LeonBlade/xnbcli/releases/latest
