### ISSUE TITLE
Error: Cannot find module '../build/Release/xxhash'

### ISSUE THREAD

**Issue by redplant0** [LeonBlade/xnbcli#17]
**Goal**

To unpack and repack Stardew Valley xnb assets offline via npm.

**Problem**

Error: Cannot find module '../build/Release/xxhash' when trying to run
`npm run unpack`
or
`npm run pack`

**Attempted solution**

1.  Installing xxhash via:
`npm install xxhash`

**Result:**
Still receiving the same error.

**System Info**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362

**Node JS Version**
Node 8.2.0

**Npm**
5.3.0

**CL error message:**

```
C:\Users\John\Desktop\xnbcli-master\xnbcli-master>npm run unpack

> xnbcli@1.0.4 unpack C:\Users\John\Desktop\xnbcli-master\xnbcli-master
> node ./xnbcli.js unpack ./packed ./unpacked

module.js:487
    throw err;
    ^

Error: Cannot find module '../build/Release/xxhash'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\John\Desktop\xnbcli-master\xnbcli-master\node_modules\lz4\lib\utils.js:4:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xnbcli@1.0.4 unpack: `node ./xnbcli.js unpack ./packed ./unpacked`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xnbcli@1.0.4 unpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John\AppData\Roaming\npm-cache\_logs\2019-06-21T18_32_51_259Z-debug.log

```

**Comment by redplant0** [comment]
**Update**

Using my Ubuntu 18.04, npm install and node-gyp rebuilt went smoothly, a stark contrast against the 5-hour attempt in Windows, which involved installing Visual Studio Build Tools using a non-user-friendly node-gyp cl interface.

Some interesting lines during installation on Ubuntu:
```
npm WARN excluding symbolic link build/Release/obj.target/lz4.node -> /home/john/Downloads/xnbcli-master/node_modules/.staging/lz4-027e3c13/node-lz4/build/Release/lz4.node

npm WARN excluding symbolic link build/Release/xxhash.node -> /home/john/Downloads/xnbcli-master/node_modules/.staging/lz4-027e3c13/node-lz4/build/Release/obj.target/xxhash.node
```

**On goal**

It turns out an internet connection is still necessary to unpack and repack xnb assets:

First run without internet access shows:

```
john@redplant:~/Downloads/xnbcli-master$ npm run unpack

> xnbcli@1.0.4 unpack /home/john/Downloads/xnbcli-master
> node ./xnbcli.js unpack ./packed ./unpacked

[ERROR] Failed to search for a new update. Application should still function normally.
(node:11766) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at /home/john/Downloads/xnbcli-master/xnbcli.js:39:34
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:11766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Second run with internet access was successful:

```
john@redplant:~/Downloads/xnbcli-master$ npm run unpack

> xnbcli@1.0.4 unpack /home/john/Downloads/xnbcli-master
> node ./xnbcli.js unpack ./packed ./unpacked

[INFO] Reading file "packed/Alex.xnb" ...
[INFO] XNB file validated successfully!
[INFO] File has been successfully decompressed!
[INFO] Successfuly read XNB file!
[INFO] Exporting Texture2D ...
[INFO] Output file saved: unpacked/Alex.json
Success 1
Fail 0
```

**Conclusion**
Program requires internet connection to work. Rebuilding the program is a lot easier on Linux than on Windows. Using Node.js and npm to run the package still requires internet connection to unpack and repack xnb assets.

Closing the issue.

**Comment by LeonBlade** [comment]
One of the issues you encountered with online is in fact a bug I'll address right now but wont push an update until I finish getting a solution for SDV 1.4 in.

**Comment by redplant0** [comment]
Found the solution by wrapping line 39 of xnbcli.js with a try and catch, and was about to issue a pull request.

**Comment by redplant0** [comment]
Found the solution by wrapping line 39 of xnbcli.js with a try and catch, and was about to issue a pull request. Thank you for addressing the issue. Looking forward for the update on windows, as I often use it more than my Linux. Thank you again.

**Comment by redplant0** [comment]
By the way, about my initial problem with **"Error: Cannot find module '../build/Release/xxhash'"** when running npm on Windows, doing these fixed the problem for me:

- Installing Visual Build Tools 2017 using Visual Installer
- Installing Node.js V 8.8.0 [Link](https://nodejs.org/dist/v8.8.0/) (Although I still got a warning when compiling lz4.node. A more appropriate version will probably fix this issue.)
- Using PowerShell as admin when building the app
