### ISSUE TITLE
Issue when trying to extract a XNB containing a 3d model

### ISSUE THREAD

**Issue by ZeroPointGaming** [LeonBlade/xnbcli#20]
![image](https://user-images.githubusercontent.com/22979867/65825181-eee13900-e241-11e9-8c4c-01ab91edc154.png)

**Comment by ZeroPointGaming** [comment]
[Zombie.zip](https://github.com/LeonBlade/xnbcli/files/3666278/Zombie.zip)
Here is the file that caused the error

**Comment by LeonBlade** [comment]
Thanks for your issue.  Currently, there is no support for extracting a 3D model, as this project was primarily created for Stardew Valley.

I may be able to add support for this feature if it isn't too much trouble.

**Comment by LeonBlade** [comment]
I just took a look at the file, one of the readers that is required to read this file is something I'm currently developing and don't have an exact ETA on when it will be available.  Unfortunately, I won't be able to whip up something quickly to support reading 3D Model files at this time.

**Comment by LeonBlade** [comment]
Closing this as I'm going to do a rewrite and this will be addressed then.

**Comment by modz2014** [comment]
3d modeling in these xnb files are hard I have ben to do this for a bit now
