### ISSUE TITLE
Won't Unpack Or Pack

### ISSUE THREAD

**Issue by RomanRocks3** [LeonBlade/xnbcli#21]
Problem:
- I Paste my File (cat.xnb)
- In Packed And Run Unpack.bat On Windows 10, 
-I Press Enter As It Says And Nothing In Unpacked Or Packed 
-This is the command prompt that It follows with

C:\Users\XXXX\Downloads\xnbcli-master>xnbcli.exe unpack ".\packed" ".\unpacked"
'xnbcli.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\XXXX\Downloads\xnbcli-master>echo Press enter to continue
Press enter to continue

C:\Users\XXXX\Downloads\xnbcli-master>pause
Press any key to continue . . .

Ok Plz Help Me

**Comment by LeonBlade** [comment]
You downloaded the wrong file, please download the latest release from here: https://github.com/LeonBlade/xnbcli/releases/latest
