### ISSUE TITLE
Possible terraria support?

### ISSUE THREAD

**Issue by CDVoidwalker** [LeonBlade/xnbcli#22]
`[ERROR] Filename: packed/Content/Fonts/Combat_Text.xnb
XnbError: Non-implemented type found, cannot resolve type "ReLogic.Graphics.DynamicSpriteFontReader", "ReLogic.Graphics.DynamicSpriteFontReader, ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
    at simplifyType (/snapshot/xnbcli/app/Xnb/TypeReader.js:0:0)
    at Xnb.load (/snapshot/xnbcli/app/Xnb/index.js:0:0)
    at processUnpack (/snapshot/xnbcli/xnbcli.js:0:0)
    at Walker.walker.on (/snapshot/xnbcli/xnbcli.js:0:0)
    at Walker.emit (events.js:189:13)
    at Object.emitSingleEvents [as emitNodeType] (/snapshot/xnbcli/node_modules/walk/lib/node-type-emitter.js:58:13)
    at Walker._wLstatHandler (/snapshot/xnbcli/node_modules/walk/lib/walk.js:88:19)
    at /snapshot/xnbcli/node_modules/walk/lib/walk.js:106:12
    at FSReqWrap.oncomplete (fs.js:154:5)`

It'd be very nice to add font types to xnbcli as it's the only thing it doesn't really support for Terraria. This'd be very nice as there's no other xnb extractor project like this one.

**Comment by LeonBlade** [comment]
I'm sorry for the late response on this.  I'm not sure when I would be able to support something like Terraria if it has custom types like this, but I can consider it in the future if you are still interested.  This project will be undergoing a complete rewrite in C# before anything.

Please let me know if you're still interested.

**Comment by CDVoidwalker** [comment]
Well I wanted to recreate Terraria in rust and that was basically the only obstacle I have encountered, yet the project is in halt and it serves only educational purposes I guess as it is just better to help [them](https://github.com/tModLoader/tModLoader) to optimalize the game, rather than to recreate it, as it would mean recreating all mods. The mods do not need to extract Terraria data themselves so it is no longer an interest of mine, and I do not believe anyone else was interested.

**Comment by SlothsAreLazyTho** [comment]
Well there is actually intrests. Is there any chance it could be explained on how to read a text file. I'd like to use it for my own TerrariaEditor. It's the last thing I would need to extract the item names. I have been reading through Terraria's code via DotPeek but no luck? Maybe anyone could explain me what reader is needed to extract them?

**Comment by LeonBlade** [comment]
@SlothsAreLazyTho I wouldn't really know since I haven't looked into modding Terraria at all. There might be another source to look to for information on this subject.
