### ISSUE TITLE
Can't extract "TailoringRecipes.xnb"

### ISSUE THREAD

**Issue by clementnader** [LeonBlade/xnbcli#25]
I can't extract the file "TailoringRecipes.xnb" in Data with xnbcli,
it's telling me that there is a "Non-implemented type found".
I was wondering if there is a way to extract it, or if you will do it in the future.

**Comment by Pathoschild** [comment]
`TailoringRecipes` uses a new data model format that's not currently supported; see #13.

**Comment by LeonBlade** [comment]
Will be supporting this in a rewrite in the near future.  Going to close for now, but I'm aware of this issue.  Thank you!

**Comment by CugeQ4920** [comment]
当我使用他解包winter_outdoorsTileSheet.xnb文件时，没有出现任何对应文件，请求帮助

**Comment by Pathoschild** [comment]
This duplicates #13, so we can probably close this one.
