### ISSUE TITLE
Core xnbcli file missing. Can't pack or unpack .xnb files.

### ISSUE THREAD

**Issue by kingliamb** [LeonBlade/xnbcli#26]
The core xnbcli file (I'm guessing it's a binary) is missing from my download. I've downloaded the zip and cloned with git multiple times. Whenever I run `unpack.sh` from the terminal, this is the result:
`$ dash unpack.sh`
`./unpack.sh: line 3: ./xnbcli: No such file or directory`
`Press enter to continue`
I don't know what's wrong but I would be happy to help in any way I can. Attached is a picture of the main xnbcli folder shown graphically in nautilus.
I'm running Ubuntu 16.04. Thank you for the help!
![Screenshot 2020-03-09 16:16:23](https://user-images.githubusercontent.com/55339220/76253749-9d41cf00-6221-11ea-9c6c-7563a0a431e6.png)

**Comment by LeonBlade** [comment]
Thanks for reporting the issue.  You should be downloading the latest release from here: https://github.com/LeonBlade/xnbcli/releases/download/v1.0.5/xnbcli-linux.zip

**Comment by kingliamb** [comment]
That link seemed to have worked. I'm not exactly sure what happened. Thanks for the quick response and help!
