### ISSUE TITLE
Using xnbcli as a module

### ISSUE THREAD

**Issue by polarstoat** [LeonBlade/xnbcli#27]
I'm having some difficulties using xnbcli as a module.

Could you add `"main": "xnbcli.js",` to the `package.json`? And consider publishing the package on npm too?

It would also help if there was a non-CLI way to use xnbcli. Exporting the `processUnpack()` and `processPack()` functions in `xnbcli.js`, for example.

**Comment by LeonBlade** [comment]
It's not really intended to be used as a module and instead is intended to be used in it's packaged form. I can look into supporting this though. I still have to get around to supporting Reflection support which is keeping me from touching this as it's a pain.

If you happen to want to make the changes yourself, please submit a PR and I will be more than happy to accept.
