### ISSUE TITLE
Xnb Error: Invalid File 

### ISSUE THREAD

**Issue by thribbyribby** [LeonBlade/xnbcli#28]
I was trying to extract an image from a .xnb file but I ran into this error:
My-MacBook-Air:~ Me$ /Users/Me/Downloads/xnbcli-macos/unpack.command ; exit;
[INFO] Reading file "packed/Coby 2 copy.xnb" ...
[ERROR] Filename: packed/Coby 2 copy.xnb
XnbError: Invalid file magic found, expecting "XNB", found ""
         at Xnb._validateHeader (/snapshot/xnbcli/app/Xnb/index.js)
         at Xnb.load (/snapshot/xnbcli/app/Xnb/index.js)
         at processUnpack (/snapshot/xnbcli/xnbcli.js)
         at Walker.<anonymous> (/snapshot/xnbcli/xnbcli.js)
         at Walker.emit (events.js:311:20)
         at Object.emitSingleEvents [as emitNodeType] (/snapshot/xnbcli/node_modules/walk/lib/node-type-emitter.js:58:13)
         at Walker._wLstatHandler (/snapshot/xnbcli/node_modules/walk/lib/walk.js:88:19)
         at /snapshot/xnbcli/node_modules/walk/lib/walk.js:106:12
         at FSReqCallback.oncomplete (fs.js:167:5)

Success 0
Fail 1

I have next to no knowledge on programming, converting files like xnb's, nor what "invalid file magic" means or how to handle it. Is there any course of action you can recommend?

**Comment by LeonBlade** [comment]
What file are you trying to unpack? Where does this come from?

**Comment by thribbyribby** [comment]
It is an asset of a character from a game I downloaded on Steam, and I duplicated the file from the Steam local files. The game is "Amorous," and the character is "Coby." The original file I duplicated is "Coby 2.xnb"

**Comment by LeonBlade** [comment]
Can you send me the file so I can take a look? This was specifically designed for SDV, but should work for other basic content files.

**Comment by thribbyribby** [comment]
https://drive.google.com/file/d/1KoDN_pLP3u9WMkHJByRMWfzpPq4Y8lnV/view?usp=sharing
I don't think it ever will show the preview, but you can still just download it

**Comment by LeonBlade** [comment]
Just took a look now, the issue is this XNB file is actually a zip file with the contents being the actual XNB. If you unzip the file first, it will work. Just confirmed that this file works as well. I would post the texture here as proof but it's NSFW. Hopefully this helps!

**Comment by thribbyribby** [comment]
Yeah, sorry about the picture being nsfw. I didn't think that would be one of the nsfw ones, but I should have mentioned that earlier. 

Thank you for all of your help, although I do have one last problem that I would like to consult you with: I don't know how to unzip the file. Whenever I try to open it on my Mac, I just get a prompt telling me that my computer will not open it because it can't verify that the file isn't malware.

 Is there some program/file I should download to do this or some command I need to run in the Terminal? If you're not sure how to do it on Mac, don't worry about it, I can look into it further on my own; I just figured I may as well try asking you first. Again, thank you for all your help prior to this

**Comment by LeonBlade** [comment]
No problem at all, doesn't bother me.

You can rename the XNB file to have .zip at the end and it should work and allow you to unzip it.

**Comment by thribbyribby** [comment]
That worked! Thank you so much for all your help, and for this useful tool! I always forget that you can sometimes just change the file type by renaming it lol. Thanks
