### ISSUE TITLE
Can't pack XNB file

### ISSUE THREAD

**Issue by Kara-bati** [LeonBlade/xnbcli#33]
I don't know if there's something very obvious that I'm missing, but I cant figure it out. I have no problem unpacking files, but when I try to repack the same file nothing happens. I do as the directions say, I put the unpacked file in the unpacked folder, then run pack.bat, but the file doesn't repack and all that comes up is this 
https://user-images.githubusercontent.com/62083131/97391420-6ac21080-189c-11eb-9f15-19eb9c06ee2b.png

I click enter and the window closes, same thing if I press any key

**Comment by LeonBlade** [comment]
What does your unpacked folder look like?

**Comment by Kara-bati** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/62083131/97398367-584dd400-18a8-11eb-93b3-2d2d48b24a2f.png)

**Comment by LeonBlade** [comment]
You're missing the JSON file associated with the texture.

**Comment by Kara-bati** [comment]
oh my god, i'm an idiot lol. I just tested it again, it works, I had a feeling it was something super obvious. thanks for helping!

**Comment by LeonBlade** [comment]
No problem.
