### ISSUE TITLE
[Solved!]Can't use xnbcli to unpack/pack

### ISSUE THREAD

**Issue by Viola-kxu** [LeonBlade/xnbcli#34]
I use the lastest the version and when I open the command window it says:

[ERROR] Failed to search for a new update. Application should still function normally.
[ERROR] RequestError: getaddrinfo ENOENT raw.githubusercontent.com raw.githubusercontent.com:443

Can you help me with it? Thanks a lot!

**Comment by LeonBlade** [comment]
Hello, thank you for the report. I will investigate now.

**Comment by LeonBlade** [comment]
Does the application not work at all?

**Comment by Viola-kxu** [comment]
I can use now!!! I don't know why but it works. Thank you!
