### ISSUE TITLE
LGPL or other license?

### ISSUE THREAD

**Issue by KatDevsGames** [LeonBlade/xnbcli#36]
Can this be offered under any more permissive license than the normal GPL. LGPL perhaps? I'm looking to use this as a DLL but my project also links other DLLs that are not GPL compatible which makes the entire operation a no-go.

**Comment by LeonBlade** [comment]
Do you have any other alternatives that work for you?

**Comment by KatDevsGames** [comment]
Well, you're already using the GPL so my assumption is that you still want a license that requires sharing changes. If that's the case, perhaps the LGPL? It's almost identical but allows things like building it into a DLL and using the DLL together with non-GPL software legally.

**Comment by LeonBlade** [comment]
I've gone ahead and amended the LGPL license to this project. The `LICENSE.LESSER` contains the LGPL license. Github has issues detecting LGPL amendments as I've noticed, however, the project does include the LGPL amendment.
