### ISSUE TITLE
Extract

### ISSUE THREAD

**Issue by amrshaheen61** [LeonBlade/xnbcli#37]
I want to extract this file how I can do that?

https://mega.nz/file/wq4nzAra#zMvux4yGmnzSFryS3Red9LcWianxPUDXjku5Y8ynxgQ

**Comment by LeonBlade** [comment]
What file is it?

**Comment by amrshaheen61** [comment]
Text file from carrion game

**Comment by LeonBlade** [comment]
Not supporting at this time.
