### ISSUE TITLE
xnbcli packed file does not work for SDV credits.xnb

### ISSUE THREAD

**Issue by Quirinea** [LeonBlade/xnbcli#39]
I'm making a Finnish translation of Stardew Valley and to be thorough, took also the credits (which is outside the saved game). 
I got this:

[Crashed.txt](https://github.com/LeonBlade/xnbcli/files/6909382/Crashed.txt)

This is from a run where I had the credits.xnb from the base game just unpacked, packed and renamed, without editing (an .xnb only renamed worked). 

The unpacked .json worked after I had stripped it of the header part leaving only the array part (this was a workround).

**Comment by Quirinea** [comment]
Why was this closed?

**Comment by LeonBlade** [comment]
Sorry, it was a mistake! Was closing some issues and hit this by accident.

**Comment by ellipszist** [comment]
An unofficial version can fix this issues #13, so we can probably close this one.
