### ISSUE TITLE
Cannot unpack Sound Effects

### ISSUE THREAD

**Issue by hgdagon** [LeonBlade/xnbcli#40]
Admittedly, the game I'm trying to unpack is not SDV, but still. I get this error for all Sound Files:

```
XnbError: Non-implemented type found, cannot resolve type "Microsoft.Xna.Framework.Content.SoundEffectReader", "Microsoft.Xna.Framework.Content.SoundEffectReader".
```

TConvert, however unpacked these files just fine.

**Comment by LeonBlade** [comment]
I can try to support the `SoundEffectReader`, but I would need a file to test it against.
