### ISSUE TITLE
Won't Unpack Or Pack 

### ISSUE THREAD

**Issue by LaShane** [LeonBlade/xnbcli#41]
C:\Windows\system32>xnbcli.exe pack ".\unpacked" ".\packed"
'xnbcli.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>echo Press enter to continue
Press enter to continue

C:\Windows\system32>pause
Press any key to continue . . .

I downloaded the latest release.

**Comment by OrcishBloodpainter** [comment]
So is a solution posted anywhere? I'm having the same problem and can't find any answers.

**Comment by OrcishBloodpainter** [comment]
Never mind, I downloaded the wrong version. My bad.
