### ISSUE TITLE
unpack.bat not working

### ISSUE THREAD

**Issue by littleBob138** [LeonBlade/xnbcli#49]
Im on windows 10, I followed all the instructions but when i run unpack.bat the command prompt says this:
"C:\Users\(my username)\Desktop\games\asset editors\xnbcli>xnbcli.exe pack ".\unpacked" ".\packed"
'xnbcli.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\(my username)\Desktop\games\asset editors\xnbcli>echo Press enter to continue
Press enter to continue

C:\Users\(my username)\Desktop\games\asset editors\xnbcli>pause
Press any key to continue . . ."

Pressing a key closes the command prompt without doing anything.

**Comment by LeonBlade** [comment]
Did you download the release or the source code? Make sure you have a release from this page according to your OS: https://github.com/LeonBlade/xnbcli/releases
