### ISSUE TITLE
Repacking Ruins the .xnb file?

### ISSUE THREAD

**Issue by Telapoopy** [LeonBlade/xnbcli#8]
When I unpack a file, then pack it back up, even when making no changes to the unpacked contents, if I try to unpack the file I just packed, I get an error message and the unpack fails.
This is the message that gets printed out:

![Error Message 2](https://user-images.githubusercontent.com/48659928/54499589-a6c77e00-48d0-11e9-968c-96201b1b8651.png)
This was after modifying the .png file

![Error Message](https://user-images.githubusercontent.com/48659928/54499588-a202ca00-48d0-11e9-866f-a92c77363be2.png)
This was after merely unpacking a file, packing it up, then unpacking the packed file.

**Comment by LeonBlade** [comment]
Thanks for creating this issue!  I was also notified of this on Discord.  The issue has been fixed in v1.0.3.
