### ISSUE TITLE
xnb Extractor Android Port

### ISSUE THREAD

**Issue by DayatXD** [LeonBlade/xnbcli#9]
Please Port This Tools to Android!

**Comment by LeonBlade** [comment]
Can you explain what you mean by this?  The tool currently supports most Android XNB files.  If you're referring to a version that runs on Android, I don't believe I will be supporting such a feature as this is a command line tool for the purposes of extracting and packing content files.

If you wish to unpack and repack content files for Android, you can do this by pulling them off your phone from the APK and onto a Windows, Mac or Linux PC and using it from there.

**Comment by DayatXD** [comment]
Via terminal command linux on android?

**Comment by DayatXD** [comment]
Can i dm via discord?

**Comment by DayatXD** [comment]
I dont know how to use it via linux

**Comment by LeonBlade** [comment]
You can see instructions on the readme on this repo under "Usage".  There's also instructions on the Wikia page on how to use it located [here](https://stardewvalleywiki.com/Modding:Editing_XNB_files).  If you're still having issues, I recommend asking on the modding channel of the official Stardew Valley Discord server.

Thanks!
